### ISSUE TITLE
Possible issue with auto refresh

### ISSUE THREAD

**Issue by regulus33** [allmarkedup/lookbook#102]
Hello!

I haven't invested much time in understanding twebsockets or ActionCable so apologies if I am missing something or not making sense.

On a rails 6.1 app we see in the logs:

```
[ActionCable] Broadcasting to reload: {:modified=>["/path/to/file/default.html.slim"], :removed=>[], :added=>[]}
```

And on the client I do see that the socket connection is ok when I manually reload the page.
`Lookbook websocket connected`
https://github.com/allmarkedup/lookbook/blob/main/app/assets/lookbook/js/lib/socket.js#L15

But this line never seems to receive the broadcast 
https://github.com/allmarkedup/lookbook/blob/main/app/assets/lookbook/js/lib/socket.js#L11

This Rails app is still using sprockets which seems like it could be a crucial detail.

Your expertise is highly appreciated. 

Thank you for this tool!

**Comment by allmarkedup** [comment]
Hey @regulus33 sorry to hear you are having troubles with this. The logs all look as I would expect so I'll need to dig into it a little more.

Can you just confirm what version of Lookbook you are using? And what browser too? And lastly, could you also let me know the path that you have [mounted Lookbook at](https://github.com/allmarkedup/lookbook#2-mount-the-lookbook-engine)? Then I can try and investigate when I have some time.

Lookbook's assets are not served via sprockets and it shouldn't really matter - but you never know. Actually, I seem to remember someone else having some issues with Turbo - are you using that in your main app?

**Comment by regulus33** [comment]
Thanks Mark for the prompt reply. I am blown away by how attentive you are to us! 

So to answer your questions:

Lookbook version: `0.9` 

browser: `chrome`

mounted at:  `/lookbook`

Yeah the sprockets thing seems like weird. I don't see any Turbo / turbolinks stuff configured. But I think I have some stuff in common with this issue https://github.com/allmarkedup/lookbook/issues/47 so I'll close this as duplicate.

This Rails app was recently upgraded to 6.1 from 5.2 and there seem to be a lot of undocumented discrepancies between the setup of action-cable in these two versions. Anyway I'll add anything else I find in that issue.

Thanks again.

**Comment by allmarkedup** [comment]
@regulus33 I'd love to say that I'm always that quick to reply but actually you just caught me as I was sitting down to look at a few issues so it was just fortunate timing :-)

If the app has been upgraded then it may indeed be actioncable-related - I wish I could figure out what causes the issue with Rails 5.x but I've been unsuccessful so far.

Good luck tracking down the problem and let me know if there is anything I can be of assistance with 👍

**Comment by regulus33** [comment]
Thanks Mark will do 👍🏼
