### ISSUE TITLE
Support descriptions for params

### ISSUE THREAD

**Issue by DRBragg** [allmarkedup/lookbook#106]
# Support descriptions for params
### Feature Request

It would be nice to be able to support adding descriptions (like helper text) to example params.  Currently we do this via the notes section but that involves toggling between the 2 tabs. Not terrible but could be better.

Since `@param` is a normal YARDoc tag but Lookbook seems to be using it in a slightly different way I'm sure this feature is much more difficult to implement than it sounds but I'm happy to help out with this if you'd like.

**Comment by allmarkedup** [comment]
Hey @DRBragg yes that is a nice idea, being able to add a description/helper text to the params that shows up in the same panel would definitely be useful.

I'll have a think about how best to implement this, the `@param` tag is already fairly overloaded but I'm sure there is a way to get a description in there without the syntax being too messy!

Another possibility would to add an `@param_info` tag (or something like that) but it would probably be better to keep it within the `@param` tag itself if it doesn't get too messy.

**Comment by DRBragg** [comment]
Yea, it may end up being a breaking change based on the current implementation. `@param_info` isn't a bad idea tho.

**Comment by allmarkedup** [comment]
@DRBragg I've just shipped v1.1.0 that has support for `@param` descriptions (plus lots of other `@param` improvements!) so I'm going to close this issue down now. Let me know what you think if you get a chance to have a play :-)
