### ISSUE TITLE
Opening preview in a new window discards query parameters

### ISSUE THREAD

**Issue by andapopovici** [allmarkedup/lookbook#118]
When opening a preview that has query parameters in the URL in a new window, these query parameters are discarded.

This might not be a bug and just how Lookbook is intended to work, but I found it surprising. I have used the Lookbook demo to illustrate the bug. 

I have tested this in:

- **Chrome** Version 103.0.5060.134 (Official Build) (x86_64)
- **Safari** Version 15.5 (17613.2.7.1.8)

# Steps to reproduce

- navigate to the [Avatar - Rounded page](https://lookbook-demo-app.herokuapp.com/lookbook/elements/avatar/)
- in the Params tab, change the size to Small
- click the Open in new window button on the top right hand side of the preview

## Expected result
The new window displays a small avatar

## Actual result
The new window displays the default avatar

**Comment by allmarkedup** [comment]
Hi @andapopovici! Thank you for the bug report and I'm really sorry it has taken so long to reply. I've been away on holiday and am just catching up on issues here.

I've tested this and it is indeed a bug - good spot :-) I'll get it fixed as soon as I can and into the next release.

Many thanks for taking the time to report it 👍

**Comment by andapopovici** [comment]
I can confirm this is now fixed in `0.9.4` which we are running in our Lookbook instance. Thanks a lot for the fix @allmarkedup !
