### ISSUE TITLE
Lookbook FS listener can hang a non-server process

### ISSUE THREAD

**Issue by netshade** [allmarkedup/lookbook#124]
We recently had an issue where, after introducing Lookbook, several of our non-server scripts ( things in the manner of `bin/run_some_database_tasks` or `bundle exec rake do_a_thing` ) would fail to exit cleanly - instead they would just hang. Investigating this, we found that there was a single `fs_event` process ( from the `listen` gem ) that was only looking at `view_component` directories. After further investigation, it appeared that by setting `config.lookbook.listen` to `false` in our application config, the fs event watching process would not be started, and our processes would exit cleanly.

Reviewing the Ruby stack traces of the processes while they were hung, it seemed like the hang could occur due to an odd interaction of the `debug` Ruby gem and the `listen` gem. 

Also, it seems like the very idea that file system watchers were initialized and running in a non-server process ( eg, a Rake task ), seems likely not intended. It is probably worthwhile to make it such that the filesystem watchers only initialize and run in cases where the application is running *as a server* and not as a script or Rake task.

**Comment by allmarkedup** [comment]
Hey @netshade, many thanks for the detailed bug report and I'm sorry that this has had to take up your time!

You are right - those file system watchers should not run in non-server processes. I've just done a little testing and determining what is and isn't a server process is harder than I had assumed, but I think I have a fix that I'll push up shortly.

Out of interest, what version of Lookbook are you using? Are you using a v1.0 beta version?

Really appreciate your help with this and I'll let you know as soon as I have a release out with a fix.

**Comment by allmarkedup** [comment]
Hey again @netshade.

I've just released `v0.9.5` that I'm hoping fixes the issue for the most part. After much tearing hair out trying to figure out how to tell a server process from a non-server one I stumbled across a pretty neat way of doing it, but it's only supported in Rails >= 6.1.3.1.

So for older versions of Rails it just checks for if it is running in a rake task (if so, it won't start listening), as this was really the only reliable check I could put together. I'll see if I can improve it in the future.

I'm going to port these changes over to the v1.0-beta branch later on and will get a new release of that out too when I can.

If you have a chance to test it and let me know if you are still experiencing any issues then that would be much appreciated :-)

**Comment by netshade** [comment]
I just tested it, and it works "sort of" for our case. Here's what's happening:

* We initialize a server process with Lookbook enabled. This *works*, as the listener starts up as desired.
* We run a rake task. This *works*, as `Rails.application.server` is nil, so then we hit your `else` case and it checks to see if we're in a `rake` task.
* We run a script that does `require "../config/environment"` to load the Rails environment. This *does not work* and the filesystem listener starts up, due to the fact that: `Rails.application.server` is `nil`, so we fail the first part of the condition you added, which takes us to the `else`, which in turn will start the listeners because `rake` is not involved in the process.

I *think* what might be intended by your commit is something more along the lines of:

```
if Rails.version >= "6.1.3.1"
  if Rails.application.server
    Rails.application.server { init_listeners }
  end
else
  init_listeners unless File.basename($0) == "rake" || Rake.application.top_level_tasks.any?
end
```

because I assume that, if you are in any Rails beyond 6.1.3.1, you don't care about the `rake` fallback, it is *only* whether or not `server` is present. ( Totally acknowledge that the explicit version check is not great, just the easiest way to communicate what's intended there. I guess you could also do `if Rails.application.public_methods.include?(:server)` or something like that too, tho I doubt anyone would say that's much "better" )

**Comment by allmarkedup** [comment]
Ok that is very helpful, thank you. I'm really a frontend dev (as you can probably tell by the state of my Ruby code!) and so my go-to approach is usually to feature test rather than compare versions. But now looking at it again after reading your explanation I can see that attempting some sort of feature detection here is totally the wrong approach. Serves me right for rushing something out :-)

Appreciate you sharing your use case details - I certainly hadn't thought through the `require` scenario so that is very helpful.

I'm going to get a branch up with the changes you suggest and then if all is good I'll get out another release with the fix.

Are you current using the `0.9.x` releases? Or the `v1.0 beta` ones?

**Comment by allmarkedup** [comment]
@netshade I've just pushed up a (0.9.x) branch called  [`server-only-listeners`](https://github.com/allmarkedup/lookbook/tree/server-only-listeners) that has (I hope!) the correct logic in it now.

With the version number test there was no need to additionally test for the presence of Rails.application.server - the block will only be run if it's in a server context anyway. 

Whenever you have a chance if you could give it another test with this branch and let me know how you get on it would be much appreciated.

Obviously the fallback for older rails versions is still far from perfect but it's still better than the way it is currently.

**Comment by netshade** [comment]
We were using the `0.9.x` release series - specifically `0.9.3`. And I just tested on your `server-only-listeners` branch for us and that works great, thank you for the quick response and your maintainership on this. And yeah, I definitely agree with your take on the older Rails version issue - locally I had put a hack into place that essentially set a global variable in our `config.ru` such that I was guaranteed that it would be only set from within a server context, and then I set `config.lookbook.listen` to true or false based on the presence of that variable. If someone else runs into this on an older Rails version, they could likely take that approach as a way to handle it in their use case.

Thanks very much for your work and maintainership on this, you're awesome.

**Comment by allmarkedup** [comment]
Ok that is great, thanks for testing it so quickly, I'll get a new release out now. And thank you for the kind words - totally made my day ☺️ 

The `config.ru` variable hack sounds like a great workaround for people if they need it, nice one. I think I'll actually try to get that added to a 'troubleshooting' section in the docs as soon as I have a chance.

Very much appreciate your help and just let me know if there is ever anything else I can help with.
