### ISSUE TITLE
Feature Request: Searching by example name + Sorting examples by alphabetical name in sidebar

### ISSUE THREAD

**Issue by afomera** [allmarkedup/lookbook#13]
Hi! 

So I haven't pulled down the latest version and gotten it to boot yet, but... one thing that would be nice, is the ability to sort the examples within the sidebar folders by alphabetical name, I've found the names to end up going all over the place.

Another feature request we have is extending the sidebar search to support by example name as well.

For some more context, here's how we're thinking of setting up our examples:

<img width="357" alt="CleanShot 2021-07-30 at 10 14 06@2x" src="https://user-images.githubusercontent.com/1741179/127681700-19b817cc-a7e8-4b6a-becd-aa481585390c.png">

and search has been mostly limited to the titles. 

If y'all have a lot of components, how do you think of organizing the Lookbook examples? We have hundreds of components at @podia 😅, and are hoping to use Lookbook to help surface them to our team. 

Additionally.... this is more of a bug, but I'm a little befuddled why the first item in my namespace `Podia::UI::` always gets added to its own list. 😭 (We have a custom inflector to make Ui -> UI with Zeitwerk, but even renaming it, it tended to push it into a new list for the first item.

**Comment by allmarkedup** [comment]
Thanks for this @afomera - the navigation and search is definitely high up on the list of things to improve. There is [another issue open](https://github.com/allmarkedup/lookbook/issues/6) with some rough thoughts on nav/search improvements, and including example titles in the filter is definitely one of them.

Looking at your example, It would also be nice to be able to specify where in the namespace to start the nav tree from (i.e. skip the Podia::UI part altogether). I'll add that to the list.

However quite why the first item ends up in its own list is an odd one - definitely a bug. I'll try to figure out why that might happen.

**Comment by allmarkedup** [comment]
Out of interest, would you want the examples for each preview sorted alphabetically too? My preference is to match the order I've defined them in the preview class, but that could quite easily be a configuration option.

**Comment by afomera** [comment]
Thanks @allmarkedup , sorry I missed that other issue. I'm sorta mixed, if it respected the order it was defined in the preview class that'd work (I may be wrong, but it doesn't seem to do this now), otherwise falling back to alphabetical order by example would be great imo, we can classify stuff ourselves that way.

TBH, we have a ton of namespaces (IE so Podia::UI is not the only one in the Podia tree), so I'm not sure if we'd want to use it, as our team has decided things in Podia::UI are 'dumb' base components we one day when we're a larger team may extract to a new gem, but have other folders and namespaces inside of them.
