### ISSUE TITLE
Documentation links same color as paragraph

### ISSUE THREAD

**Issue by Jackson200** [allmarkedup/lookbook#142]
Hello,
Can't get enough of Lookbook. Thanks for your work @allmarkedup 
I noticed the links are `color: inherit` in the documentation, so are invisible against the paragraph.

See https://lookbook.build/api/entities/preview/ for an example.

![Screen Shot 2022-09-08 at 9 18 53 PM](https://user-images.githubusercontent.com/39567695/189252297-d6ea91bc-c07f-434c-bed2-faf676a0155f.png)

I almost missed a treasure trove of info :)

**Comment by Jackson200** [comment]
I see the rule:

```
.prose :where(a):not(:where([class~="not-prose"] *)) {
    color: var(--tw-prose-links);
    text-decoration: underline;
    font-weight: 500;
}
```

on other pages like https://lookbook.build/guide/previews/annotating/

I can't see why it isn't picked up on the page with the issue.

**Comment by allmarkedup** [comment]
@Jackson200 my pleasure, really happy that you are so into it!

Good spot with the link styling issue - will get that fixed now, thank you :-)
