### ISSUE TITLE
`preview_disable_action_view_annotations` config has no effect on preview layout filename annotation

### ISSUE THREAD

**Issue by thutterer** [allmarkedup/lookbook#151]
This is a small follow-up to #146.

When ViewComponent is configured to use a custom layout (`config.view_component.default_preview_layout`) then Lookbook still annotates every preview with the filename of that layout: 

![image](https://user-images.githubusercontent.com/5372947/191004766-7a75327a-8478-4a6a-94fb-5bd7849625c0.png)

**Comment by allmarkedup** [comment]
Hey @thutterer, thanks for pointing this out - I'll get this fixed up and let you know when it's going out in a release 👍

**Comment by allmarkedup** [comment]
@thutterer I'm actually unable to recreate this locally for some reason but I can see where it could creep in so I think I've now fixed the issue.

Would you be able to install Lookbook from the `fix-view-annotations-removal-with-custom-layout` branch and just let me know if it fixes the problem for you?

You can target the repo/branch using the following in your `Gemfile`:

```rb
gem 'lookbook', git: 'git://github.com/allmarkedup/lookbook.git', branch: 'fix-view-annotations-removal-with-custom-layout'
```

And then running `bundle update lookbook`. If that does the trick I'll merge in the fix and get it out in the next release.

**Comment by allmarkedup** [comment]
Awesome, thanks for testing it and letting me know @thutterer, much appreciated. I'll merge it in now!
