### ISSUE TITLE
Error when disabling View Component monkey patching

### ISSUE THREAD

**Issue by dlupu** [allmarkedup/lookbook#156]
I'm working on a Ruby on Rails 6.0 app where we need to disable the ViewComponent monkey patching. 

   `config.view_component.render_monkey_patch_enabled = false # default is true` 
   
When we do that lookbook breaks with the following error 

> '#<Lookbook::SplitLayout::Component:0x00007fec7bfc0d90 @alpine_data="$store.layout.main", @html_attrs={:":class"=>"$store.layout.mobile && '!block'"}>' is not an ActiveModel-compatible object. It must implement :to_partial_path.

Has anyone else had this problem? 

<img width="1439" alt="Screenshot 2022-09-21 at 16 38 04" src="https://user-images.githubusercontent.com/247936/191534248-85faf046-8d29-4d06-83bc-c43ae91173a4.png">

**Comment by allmarkedup** [comment]
Hey @dlupu - this will be because Lookbook is using ViewComponent under the hood and is using `render` rather than `render_component` to render it's own components, which breaks without the monkey patch.

Obviously it should not break like this, it's a bug and I'll get this fixed up as soon as I can and included in the next release. Thanks for opening the issue and bringing it to my attention 👍

**Comment by allmarkedup** [comment]
Hey @dlupu I believe I have a fix for this now - if you have a spare moment to install Lookbook from the `fix-monkey-patch-disabled-errors` branch and let me know if it works now that would be much appreciated.

You can add it to your `Gemfile` like this:

```rb
gem 'lookbook', git: 'git://github.com/allmarkedup/lookbook.git', branch: 'fix-monkey-patch-disabled-errors'
```

And then run `bundle update lookbook` in the terminal. Let me know how you get on :-)

**Comment by allmarkedup** [comment]
@dlupu I've now merged in that PR and this fix will go out in the next release. If you still have any problems after updating please feel free to re-open this and let me know! Thanks again for bringing it to my attention.
