### ISSUE TITLE
Add ability to render multiple preview examples in one window

### ISSUE THREAD

**Issue by allmarkedup** [allmarkedup/lookbook#30]
Maybe by using a `@group` tag?

Would mean just one link in the navigation for all examples in that group, and the group's items would be rendered together in one preview window.

**Comment by Spone** [comment]
That would be awesome, especially for components like buttons that have a lot of variants but take very few space on the screen :)

**Comment by allmarkedup** [comment]
Added in [v0.3.0](https://github.com/allmarkedup/lookbook/releases/tag/v0.3.0)
