### ISSUE TITLE
ActionCable appears to still be triggering periodic requests even though auto_refresh is set to false

### ISSUE THREAD

**Issue by edwinthinks** [allmarkedup/lookbook#36]
I noticed in my logs that ActiveCable seems to continuously be polling for changes by making requests periodically. I suspect that if `auto_refresh` is set to false, it shouldn't be occurring?

**Comment by allmarkedup** [comment]
Hey @edwinthinks - this should be fixed now with the [v0.2.2 release](https://github.com/allmarkedup/lookbook/releases/tag/v0.2.2) that I just pushed up - if you are still having any issues with it just let me know. Thanks!
