### ISSUE TITLE
lookbook must be after view_component in the Gemfile

### ISSUE THREAD

**Issue by Spone** [allmarkedup/lookbook#37]
Hi, thanks for your work on this awesome project!

I just discovered that the 

    gem "lookbook"

declaration **must** be after

    gem "view_component", require: "view_component/engine"

in the `Gemfile`, else you get this error when trying to show a preview:

```
NoMethodError in Lookbook::BrowserController#show
undefined method `constantize' for nil:NilClass

lookbook (0.2.1) app/controllers/lookbook/browser_controller.rb:133:in `preview_controller' 
```

In my case it was before because they were sorted alphabetically :)

What could be done to prevent this unexpected error?

Maybe add an explicit error message in this case? Add a mention in the README?

**Comment by allmarkedup** [comment]
Hey @Spone  - thanks for pointing this out. It _was_ actually originally mentioned in the installation instructions but I did a bit of a docs re-write not long ago and it seems to have fallen out then! I'll add a note back in, thanks 👍

**Comment by allmarkedup** [comment]
I've [update the installation instructions](f72ebb9904eddde0fa71c47628ace3c8774903f7) now to hopefully make this clear, and when I have a little more time I'll also see if a more explicit error can be thrown if anyone misses the note in the docs.

Thanks again for point it out :-)
