### ISSUE TITLE
Add HTML beautifier

### ISSUE THREAD

**Issue by nicolas-brousse** [allmarkedup/lookbook#39]
Hi! We are testing this pretty gem on one of our project, and I notice a small thing.

We use SLIM for views, and SLIM render html in one line.

Do you think, output tab content may use a prettier or a beautifier to show HTML?

![Screenshot 2021-09-03 at 11 26 02](https://user-images.githubusercontent.com/699216/131983358-03e00044-5910-4935-ab15-f584f363dd80.png)

**Comment by Spone** [comment]
It would also be useful to correct broken HTML source indentation when using ERB!

**Comment by allmarkedup** [comment]
@nicolas-brousse thanks for the suggestion and yes this would definitely be good - a single line of html is never too useful! It should be straightforward to add too I think.

I've briefly looked at [HTMLBeautifier](https://github.com/threedaymonk/htmlbeautifier) before which looks like it should do the job, I'll see if I can give it a proper test at some point soon and then look to get it integrated if it's going to work. @Spone it sounds like it should work for ERB indentation so could certainly be added to the source tab too.

**Comment by Spone** [comment]
> @Spone it sounds like it should work for ERB indentation so could certainly be added to the source tab too.

It wasn't clear, but I was actually talking about the _Output_ tab too. Here is an example of broken indentation generated by a component with an ERB template:

![image](https://user-images.githubusercontent.com/38524/132183409-13397b5b-5b02-4dba-b673-4457a0dd5efc.png)

I agree that HTMLBeautifier seems like a good tool for the job!

**Comment by allmarkedup** [comment]
Added in [v0.3.0](https://github.com/allmarkedup/lookbook/releases/tag/v0.3.0)
