### ISSUE TITLE
Layout broken in 0.3.0.beta.0

### ISSUE THREAD

**Issue by nicolas-brousse** [allmarkedup/lookbook#45]
Hi @allmarkedup,

I just tested your beta release, and notice an issue on layout. It looks broken on my browser (test on linux elementary OS Chromium and Firefox). Until I open folder to make tree size use all browser height.

![Screenshot from 2021-09-20 21 59 00](https://user-images.githubusercontent.com/699216/134067363-26b5cb69-d78b-4e93-9918-e64dddefffac.png)

Otherwise nice new release :rocket:

**Comment by allmarkedup** [comment]
Thanks for the quick heads up @nicolas-brousse - I used the `fill-available` property value to try to fix some small-screen browser issues clearly I should have checked browser support for it closely first!

I'll look at getting that fixed now and get an updated release out as soon as I can :-)

**Comment by allmarkedup** [comment]
@nicolas-brousse I've just published v0.3.0-beta.1 which should fix the issue - if you are still having issues let me know!

**Comment by nicolas-brousse** [comment]
@allmarkedup thanks! It seem to be fixed now :ok_hand:
