### ISSUE TITLE
Components having a single preview: nav label

### ISSUE THREAD

**Issue by Spone** [allmarkedup/lookbook#46]
I'm testing the `0.3.0.beta.2` version. Some of my components have a single preview method, named `default` (which is the default :smile: ). In this case, they are displayed as "Default" in the navigation. I would expect them to use the name of the component instead.

![image](https://user-images.githubusercontent.com/38524/134879668-0f0ed69b-7aaa-4557-af21-2dec1ff46bd0.png)

**Comment by allmarkedup** [comment]
Hey @Spone yep that is a bug! I've just pushed up a proper v0.3.0 release that includes a fix for this.

I'm going to close this now but feel free to reopen if you are still having issues. Thanks :-)
