### ISSUE TITLE
UI auto-refresh doesn't work in Rails 5.x

### ISSUE THREAD

**Issue by allmarkedup** [allmarkedup/lookbook#47]
Websocket events are being sent from the server correctly, and the websocket client connects ok, but events are never received on the client side.

**Comment by muriloime** [comment]
Hm, I noticed this in a rails 7 application too. Still investigating , but your description fits well what we're seeing

**Comment by allmarkedup** [comment]
Hey @muriloime - thanks for the information, I've been pretty busy over the last few weeks so haven't had a chance to look into this for Rails 7 yet. I'll hopefully have some time later this week to dig into it and will let you know if I make any progress on the issue.

**Comment by muriloime** [comment]
Sorry for the unstructured responses. Each time I have an idea I come back to this issue =)  In the case it helps, I am sending more info: 


I see some differences in the websocket connections between a working and a non working app:

Working: (greenfield rails 7 ) 

![image](https://user-images.githubusercontent.com/3075654/154123762-84439aef-a0ad-4bf4-89e8-bc6a95aed5c7.png)
![image](https://user-images.githubusercontent.com/3075654/154123988-e037dbec-2a3b-4ab0-84b5-25c5b159a4a5.png)

Non working ( brownfield rails 7) 

![image](https://user-images.githubusercontent.com/3075654/154123932-4c021ebc-bd78-4901-86dd-4d2ee49100bd.png)
![image](https://user-images.githubusercontent.com/3075654/154124063-54222b5e-1851-45fd-9b84-ddf1f3f27572.png)

**Comment by allmarkedup** [comment]
Hey @muriloime I've tested with a clean install of Rails 7 and have confirmed the the auto refresh is working fine for me, so it may well be something specific to your app.

I've just released v0.6.0 that has a change to the default way that the preview iframe renders it's contents. It's pretty unlikely that this will help your issue in any way but maybe you could give it a try and just confirm that you are still having the same problem?

**Comment by xdmx** [comment]
I'm also having a problem of auto refresh not working on a rails 7 app (and not even on inline components, as reported in #90). It's a quite new app and I haven't touched the config that much. For what it's worth I'm using importmaps with tailwind.

Like the above screenshot I see the "Lookbook websocket connected" log, but checking the data on the socket I see the ping, but nothing else. I've tried with both the redis and async adapter.

**Comment by regulus33** [comment]
My issue is almost the same as:
Similar to https://github.com/allmarkedup/lookbook/issues/47#issuecomment-1040619002

I see the connection starts but no broadcast is received by the client.

**Comment by regulus33** [comment]
UPDATE: we solved it (by accident you might say). We had been using Iodine for our app server in development and recently switched back to Puma. Now everything works beautifully.

**Comment by xdmx** [comment]
Just to follow up on my comment above if it could help to others, after reading #98 I tried to disable workers in my development Puma config and now I get the auto refresh working,

**Comment by allmarkedup** [comment]
Closing this issue as the websocket problems have now been resolved as of Lookbook `v1.0.5`, so UI auto-refresh should finally now work for Rails 5.x apps now 😀

**Comment by muriloime** [comment]
FYI, I solved my issues above by setting `WEB_CONCURRENCY=0` in puma
