### ISSUE TITLE
Various small bugs

### ISSUE THREAD

**Issue by dmorgan-fa** [allmarkedup/lookbook#55]
Hey, my team and I are really glad to have found Lookbook. We've only recently started using it, but we've been really impressed so far and are really hopeful it'll continue to grow.

I've noticed a few bugs and wanted to bring them to your attention, here's [a PR](https://github.com/allmarkedup/lookbook-demo/pull/2) demonstrating the issues I've uncovered:
- Multiple toggles in a components param tab don't move independentally
- Background colour still requires quotes, however [the README has dropped this information](https://github.com/allmarkedup/lookbook/commit/e68487c9282ecc66838a09b943be3d0e66b429f3#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
- _Something_ is causing the Source tab output to append lines when toggling between different select options

Thanks again for your work with Lookbook! 👍

**Comment by allmarkedup** [comment]
Hey @dmorgan-fa - great to hear that it's been useful to you and really appreciate the bug reports. I think there were a few regressions in the last release I put out (which had a lot of frontend changes in it).

I'm hoping to do another release towards the end of this week which I'll make sure include fixes for the issues you are seeing. I've only just got back from holiday so have a little catching up to do but should be able to get it out by the weekend I think.

The PR on the demo repo is super helpful so thank you!

**Comment by allmarkedup** [comment]
Hey @dmorgan-fa 👋 

I've just pushed up a [v0.5.0 beta release](https://github.com/allmarkedup/lookbook/releases) (v0.5.0.beta.1) that has a bunch of updates and fixes in it. It should fix all the issues you were seeing - I've checked on the demo PR you opened and the issues you highlight appear to be resolved.

The one exception is the quoting of colour hex codes in `@display` tags - they actually _do_ need quoting (the `#` is a special character in YAML) so I've corrected the docs to reflect that and added a note about when quotes might be needed for strings.

If you have a chance at all to kick the tyres on the beta and double check the fixes I'd much appreciate it. There are some UI improvements around the drawer in this release (amongst other things) and any more 'general' feedback on changes is also always very welcome.

Thanks again :-)

**Comment by dmorgan-fa** [comment]
Hey @allmarkedup, thanks for following up and the quick turn around. I've just checked out the latest beta (`v0.5.0.beta.2`) locally and it's all working well -- really liking the drawer improvements! 👏 

The background colour is fine, I was more raising it as a documentation bug rather than implementation. Thanks for resolving it.

I do have a follow-up question that I'll submit separately, along with another demo example.

Thanks!
