### ISSUE TITLE
Support nested rendering and/or support params in erb examples

### ISSUE THREAD

**Issue by dmorgan-fa** [allmarkedup/lookbook#57]
Hey @allmarkedup, I've created a [PR](https://github.com/allmarkedup/lookbook-demo/pull/3) demonstrating the issue.

The end-goal for us is to be able to host a Lookbook instance, and `iframe` in the rendered components into our reference site (and likely pull the code examples too), so being able demonstrate composability of our ViewComponents, is really important (i.e. an autogrid layout with various cards within).

[BAOAgency's Polaris ViewComponents](https://github.com/baoagency/polaris_view_components) example has a nice solution whereby they're using `erb` examples, called from by the ruby files. This works really well, and we're planning on following this method for all our components, but it does mean the `params` support no longer works (unless I'm missing something).

Is this something you've considered?

Thanks,
\- D

**Comment by allmarkedup** [comment]
@dmorgan-fa thanks for this - I've replied in detail on the example PR to keep the context of the questions intact. Hope it helps clear things up!
