### ISSUE TITLE
Is there slot issue?

### ISSUE THREAD

**Issue by ramontayag** [allmarkedup/lookbook#61]
Before I start digging in, I wanted to report an issue with lookbook and slots.

```ruby
    def default
      component = NavBar::Component.new do |c|
        c.main_navigation_item text: "Home", href: "#"
        c.main_navigation_item text: "About", href: "#"
        c.user_sign_out_link href: "#", confirm: "Are you sure?"
      end
      render component
    end
```

The rest of the component renders fine, but it's as if the slots are not defined at all.

Is this a known issue?

**Comment by allmarkedup** [comment]
Hey @ramontayag - slots should work as expected in Lookbook, it should be identical to how the previews work in 'regular' ViewComponent previews.

**Comment by ramontayag** [comment]
Thanks. I'll close this then and dig deeper soon. Will have a few hours next week. Will reopen if needed.

**Comment by allmarkedup** [comment]
Ok great - I'll also try to double check it later today but I use slots heavily myself without issue so it should all work as expected. Any questions about it however just let me know 👍

**Comment by ramontayag** [comment]
I found the issue. It's confusing, but the block is supposed to be passed to render and not the component:

In your case:

```ruby
component = NumberedListComponent.new

render component do |c|
  list.item "..."
end
```

**Comment by foca** [comment]
Interesting. The `#component` helper we're using should be doing that.

And doing this:

``` ruby
    def default
      component = NumberedListComponent.new
      render component do |list|
        list.item 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
        list.item 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis libero.'
        list.item 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
      end
    end
```

Doesn't render anything in the preview. I'll dig further, but maybe worth re-opening this issue, @allmarkedup?

**Comment by allmarkedup** [comment]
Hey @foca, thanks for the report but I don't think this is a Lookbook issue - I've taken a look at your code and I think you are not actually using slots correctly, as far as I can see. This is nothing to do with Lookbook but is rather the way that ViewComponent expects you to render your slots.

In the `call` method on the ListComponent you are rendering the `content` within the `ol` tag. However what you should be doing is rendering the output of all the `items` instead. Something like this (a simplified version of your code) should work:

```ruby
class Elements::ListComponent < ViewComponent::Base
  renders_many :items, "ItemComponent"

  def call
    tag.ol do
      safe_join(items)
    end
  end

  class ItemComponent < ViewComponent::Base
    def initialize(contents = nil)
      @item_contents = contents
    end

    def call
      tag.li(@item_contents || content)
    end
  end
end
```

If you look at the ViewComponent docs for slots you can see in the [`blog_component.html.erb`](https://viewcomponent.org/guide/slots.html#:~:text=end%0A%20%20end%0Aend-,%3C%25%23%20blog_component.html.erb%20%25%3E,-%3C%25%3D%20header%20%25%3E%0A%0A%3C%25%20posts.each) example that the posts are output in an `each` loop like this:

```erb
<% posts.each do |post| %>
  <%= post %>
<% end %>
```

which is just an ERB equivalent way of doing something similar to `safe_join(items)` in the `call` method.

I hope that make sense! Let me know how you get on, but as I say this is nothing specific to Lookbook so you might want to dive into the ViewComponent [discussions] if the example above isn't clear.

**Comment by foca** [comment]
🤦🤦🤦

Thank you **so much**, that was it. I stared at this for a long time trying to understand whether I was doing something wrong or not. 🙈

I also want to thank you for Lookbook and the time you put into it. It's a fantastic library and it was core to selling the use of ViewComponent within our org. ❤️

**Comment by allmarkedup** [comment]
@foca Ah great, glad that fixed it :) And thank you for your kind words, it always means a lot to hear that people are finding it useful. And if you run into any other issues just let me know 👍
