### ISSUE TITLE
Documentation Pages markdown rendering has `disable_indented_code_blocks` true

### ISSUE THREAD

**Issue by stevegeek** [allmarkedup/lookbook#64]
Thanks for `lookbook`, great gem and looking forward to moving our markdown docs into lookbook pages!

Just wondering why the Pages feature prevents the use of indented code blocks? (`disable_indented_code_blocks: true`)

Is there a specific reason this is required or could this be a user choice?

**Comment by allmarkedup** [comment]
Hey @stevegeek, glad you are getting on well with it :-)

The reason indented code blocks are disabled is that I've previously run into a few issues before when mixing markdown and a templating language (like ERB) when whitespace control has been a little tricky, and that doesn't always play nicely with indented code blocks. So i made the decision to disable it for safety as a default setting, although to be honest I don't think those issues will be seen by many people so it may just be me being over-cautious!

There is an (currently undocumented, but safe to use) setting option available for you to customise the markdown parser configuration if you wish to enable this for your project> The following code inside you `application.rb` (or env-specific config file) should do the trick:

```ruby
config.lookbook.markdown_options = {
  disable_indented_code_blocks: true
}
```

If you run into any issues let me know, and I'll try to put some test cases together to decide if I should change the default value to `true` at some point in the future.

**Comment by stevegeek** [comment]
Thanks @allmarkedup ! Great to know there is an setting for it, will try it out. If I come across any edge cases I will open a ticket for them so you have some extra data points.

**Comment by allmarkedup** [comment]
@stevegeek That would be great, thank you! 👍
