### ISSUE TITLE
Getting undefined method component error

### ISSUE THREAD

**Issue by amree** [allmarkedup/lookbook#66]
Hey guys, not sure if this is the best place to ask, but here it goes:

I keep on getting this error on my local:

<img width="1324" alt="Screenshot 2022-03-25 at 12 27 14 PM" src="https://user-images.githubusercontent.com/424392/160054682-410a39cb-3346-4f09-b5c1-22a290b01503.png">

I can load http://localhost:3000/lookbook just fine, but when I want to preview one of the components, it throws that error. I can also view the component just fine from http://localhost:3000/lookbook/example/with_default_title (one of them)

Here are my code:

```ruby
# app/components/example_component.rb

class ExampleComponent < ViewComponent::Base
  def initialize(title:)
    @title = title
  end
end
```

```erb
<!-- app/components/example_component.html.erb -->

<span title="<%= @title %>"><%= content %></span>
<%= @title %>
```

```ruby
# test/components/previews/example_component_preview.rb
class ExampleComponentPreview < ViewComponent::Preview
  # 🎉 Button playground! 🎉
  # -----------------------
  # You can use the controls in the 'Params' section
  # to set button property values on the fly.
  #
  # @param title text
  def with_default_title(title: "hello")
    render_with_template(locals: {
      title: title
    })
  end

  def with_long_title
    render(ExampleComponent.new(title: "This is a really long title to see how the component renders this"))
  end

  def with_content_block
  end
end
```

```erb
<!-- test/components/previews/example_component_preview/with_content_block.html.erb -->
<%= 
  render(ExampleComponent.new(title: "This component accepts a block of content")) do
    tag.div do
      content_tag(:span, "Hello")
    end
  end
%>
```

```erb
<!-- test/components/previews/example_component_preview/with_default_title.html.erb -->
<%= render(ExampleComponent.new(title: title)) %>
```

My current environment:
- Rails v5.2.5
- view_component v2.51.0
- lookbook v0.7.1

Let me know if you need more information. Thanks in advance.

**Comment by allmarkedup** [comment]
Hey @amree - this is definitely the best place to ask :-) Sorry you are having issues and thanks for the detailed report -  I can't see anything obviously wrong with any of those files so it may well be a bug in the latest release.

If possible could you try switching to v 0.6.1 and letting me know if you see the same issue? And I'll try and dig a bit deeper into this as soon as I can.

**Comment by allmarkedup** [comment]
Hey again @amree,

So I've tried recreating your issue and I can't seem to do it. I've created a Rails v5.2.5 test app (with Lookbook v0.7.1 and ViewComponent v2.5.1) and added the example components that you outlined and it all seems to work fine for me.

I've pushed the app up [to a repo here](https://github.com/allmarkedup/lookbook-rails-5.2.5-test) - if you have any time to pull that down and give it a spin it would be great to know if you see the same issue on that repo. If not then I will have try to think of some other ways to investigate it.

Many thanks :-)

**Comment by allmarkedup** [comment]
I haven't heard back from you @amree about this issue and I can't replicate it so I'm going to go ahead and close this. If you are still having problems feel free to reopen!

**Comment by amree** [comment]
@allmarkedup Sorry about this. But yeah, let's close it first as I'm not sure when I can explore this again. I will update here if there's any new changes.

Thanks for looking into this, really appreciate it.

**Comment by allmarkedup** [comment]
@amree no worries at all! Do let me know if you try again and run into issues or if there is anything else I can help out with 👍
