### ISSUE TITLE
ViewComponent::Preview.all returns empty 

### ISSUE THREAD

**Issue by muriloime** [allmarkedup/lookbook#68]
[follow up of https://github.com/github/view_component/issues/1252 ]

description: 

ViewComponent::Preview.all returns [] after a component.rb file changes. I managed to fix it by removing  [this line in view_component](https://github.com/github/view_component/blob/8e027ee6e2d8bf47233be165bd02ee1d48b3575e/lib/view_component/preview.rb#L33) ).

But I think @allmarkedup has a solution directly in lookbook 

Many thanks

**Comment by allmarkedup** [comment]
Hey @muriloime - thanks for this. I actually have recently pushed up a beta release (v0.7.2.beta.1) that I hope will fix this problem for you. If you have a chance could you give it a test and let me know how you get on?

**Comment by muriloime** [comment]
Wow . big changes, with nice visual @allmarkedup. I am taking a look, but still trying to make it work, since my lookbook broke with 0.7.0 version

**Comment by muriloime** [comment]
So @allmarkedup I managed to fix some errors with the current version , and created two PR to solve the problems I found: https://github.com/allmarkedup/lookbook/pull/70 and https://github.com/allmarkedup/lookbook/pull/69. 

Even though it works now, I am still seeing much more activity than expected in my server. Still investigating

**Comment by muriloime** [comment]
@allmarkedup  I managed to test the v0.7.2.beta with help of above PRs , but version > 0.7 is veeery slow for my app ( hundreds of previews). I am rolling it back to 0.6.1 for the moment. Will come back to it in a few days. 

many thanks

**Comment by allmarkedup** [comment]
hey @muriloime, many thanks for you help with this - I'm also seeing some performance issues so will have to revisit it when I have a little more time to investigate properly.

Very much appreciate your time and I'll let you know when I've managed to resolve things.

**Comment by muriloime** [comment]
@allmarkedup in the case it helps: from what I saw yesterday , it seems like it's rendering every component in every click/refresh

**Comment by allmarkedup** [comment]
Thanks @muriloime - I'll hopefully have some time to look into it over the next few days and try to work on the performance issues.

The main problem is that the ViewComponent `descendants`  list gets messed up if any of the preview files have a syntax error or similar in there, and that list needs to be repopulated. I've tried to solve it by comparing the number of expected preview files to the number of Preview class instances (as reported by `ViewComponent::Preview.all`), and reloading descendants if they don't match up. But it seems to not be working correctly in all cases, leading to everything being re-imported every request, which is obviously making things slower.

I'll let you know when I have another beta version up to test again. Thanks again for your patience!

**Comment by allmarkedup** [comment]
@muriloime I've just released another beta version that removes some potential duplicate-requiring of preview files (amongst other things). I'm hoping this helps resolve the performance issues you are seeing (although it is still possible that the strategy used for re-requiring dependencies might still be a problem for you for some reason).

If you have any time to test it and let me know if it's still significantly slower than the 0.6.x release for you then that would be really helpful.

**Comment by muriloime** [comment]
Hi @allmarkedup  I am still seeing slowness a lot of activity in the server when navigating through lookbook v0.7.2.beta.4 

here is some of the server output (I am using the updated version of the gem locally in line with main ), the log is flooded with these partials: 

```
11:12:14 web.1  |   Rendered /home/murilo/code/learn/lookbook/app/views/lookbook/components/_icon.html.erb (Duration: 0.1ms | Allocations: 17)
11:12:14 web.1  |   Rendered /home/murilo/code/learn/lookbook/app/views/lookbook/components/_icon.html.erb (Duration: 0.1ms | Allocations: 17)
11:12:14 web.1  |   Rendered /home/murilo/code/learn/lookbook/app/views/lookbook/components/_nav_preview.html.erb (Duration: 0.1ms | Allocations: 21)
11:12:14 web.1  |   Rendered /home/murilo/code/learn/lookbook/app/views/lookbook/components/_nav_group.html.erb (Duration: 1.1ms | Allocations: 509)
11:12:14 web.1  |   Rendered /home/murilo/code/learn/lookbook/app/views/lookbook/components/_nav_collection.html.erb (Duration: 1.2ms | Allocations: 595)
11:12:14 web.1  |   Rendered /home/murilo/code/learn/lookbook/app/views/lookbook/components/_nav_group.html.erb (Duration: 2.1ms | Allocations: 1017)
11:12:14 web.1  |   Rendered /home/murilo/code/learn/lookbook/app/views/lookbook/components/_nav_collection.html.erb (Duration: 2.3ms | Allocations: 1103)
11:12:14 web.1  |   Rendered /home/murilo/code/learn/lookbook/app/views/lookbook/components/_nav.html.erb (Duration: 2310.1ms | Allocations: 2006932)
11:12:14 web.1  |   Rendered /home/murilo/code/learn/lookbook/app/views/lookbook/components/_sidebar.html.erb (Duration: 4214.9ms | Allocations: 4044277)
11:12:14 web.1  |   Rendering /home/murilo/code/learn/lookbook/app/views/layouts/lookbook/skeleton.html.erb
```

**Comment by allmarkedup** [comment]
@muriloime ok so the partial output logging is actually expected - that is just the (heavily partial-ized) UI being rendered. Previously Lookbook had unintentionally disabled the main action_view logger in the parent app which is why all that noise wasn't present before. I will look for another option to remove that from the console, but that in itself shouldn't affect the performance (it has always actually been built that way). 

I'm a little stumped now as to why the 0.7.x release is slower for you than the 0.6.x branch, but I don't want to take up any more of your time on this as you have been very helpful already. I think I probably need to go back to the drawing board a bit and see if I can auto-generate a very large number of test components to better recreate the performance issues at my end and work from there.

Many thanks again - once I've got a bit of a better test setup and start seeing some improvements I'll let you know.

**Comment by allmarkedup** [comment]
@muriloime ok I lied :-) One last try, if you have any patience left... v0.7.2.beta.5 enables some preview caching which in my tests has sped up the UI rendering a lot. Let me know if you see any improvement if you get a chance to try it!

**Comment by muriloime** [comment]
@allmarkedup dude, stop lying !! :laughing: From my side, all good. Performance seems perfectly fine now

**Comment by allmarkedup** [comment]
😂 Well that is great news... thank you for testing it one last time! I'm going to go ahead and close this issue now but please do open another if you run into any more issues.
