### ISSUE TITLE
The action 'show' could not be found for Lookbook::PreviewsController

### ISSUE THREAD

**Issue by mdrbohlav** [allmarkedup/lookbook#71]
When I try to display any component I get an error `The action 'show' could not be found for Lookbook::PreviewsController`. The main page works, all the components are loaded in the left menu but when I select any of them the error appears.

Any suggestions please? In the `Gemfile` the `gem 'lookbook'` is AFTER the `gem 'view_component', require: 'view_component/engine`.

EDIT: Found the issue, my ViewComponent gem was version 2.25 where `ViewComponent::ComponentError` used in the `Lookbook::PreviewsController` is not defined.

**Comment by allmarkedup** [comment]
Hey again @mdrbohlav - I see you have closed this issue but I just wanted to check to see what the problem was in the end? I'm wondering if it may be something similar to issue #66 so it would be good to know how you solved it if you have a chance to let me know. Thanks!

**Comment by mdrbohlav** [comment]
@allmarkedup I fixed it by updating gem `view_component` to the latest version `2.52`. The previous one (`2.25`) did not have defined `ViewComponent::ComponentError` used in the `Lookbook::PreviewsController`.

**Comment by allmarkedup** [comment]
@mdrbohlav ah okay, that is very useful to know, thank you. In that case it should be fixed in the latest 0.7.2 beta anyway but if anyone else comes across the same issue I can ask them to upgrade the ViewComponent version (or use the beta until it's released).

Very much appreciate the reply, many thanks 👍
