### ISSUE TITLE
Params are empty for grouped previews

### ISSUE THREAD

**Issue by mdrbohlav** [allmarkedup/lookbook#72]
The `params[:lookbook][:display]` is empty for grouped previews no matter what and where I try to set.

**Comment by allmarkedup** [comment]
Thanks for the report @mdrbohlav - I'll try and take a look at this as soon as I can.

In the meantime could you let me know which version of Lookbook you are using to help me track down the issue?

**Comment by mdrbohlav** [comment]
@allmarkedup Thank you, I'll try to debug it as well but I just found this gem so it might take a little more time.
I am using version `0.7.1`.

**Comment by allmarkedup** [comment]
Hi @mdrbohlav - I've just released a beta version (v0.7.2.beta.4) that should address this issue. If you could give it a test and let me know if it fixes things for you that would be great.

It's worth noting that `@display` params work slightly differently for grouped previews - all of the `@display` values set on the examples in the group are merged together as they are all rendered in the same layout. So you only really need to set the `@display` values on one of the examples in the group.

Hope that makes sense and let me know how you get on if you get a chance to try the beta version.

**Comment by mdrbohlav** [comment]
@allmarkedup Merging the params in the group seems logic. Looks good in the beta 4, thank you for the quick response!
