### ISSUE TITLE
Markdown landing support seems to have broken default routes for components

### ISSUE THREAD

**Issue by dmorgan-fa** [allmarkedup/lookbook#81]
Hey Mark, really impressed with the new experimental pages functionality!

One small things I've noticed so far:
- Previously you could navigate to `<lookbook>/components/card` and it would redirect to the top preview as the default (i.e. `<lookbook>/components/card/default`). I _think_ since the `landing` support with YAML Frontmatter, we're now hit with a "Preview Not Found" error instead

I've spotted a few documentation issues, so I've raised PR's against them as well.

Cheers!

**Comment by dmorgan-fa** [comment]
Adding another small note:
`sidebar-open` seems to be `false` by default on previous versions (i.e. `0.6.1`) so when you upgrade, or someone else visits the upgraded UI for the first time, the sidebar is collapsed by default.

Clearing out the local storage, and reloading the page has the sidebar open by default.

(Spotted by @andapopovici)

**Comment by allmarkedup** [comment]
Hey @dmorgan-fa - sorry for the slow replies, I've been away for a bit over Easter so just catching up with everything.

I'll take a look at those issues tonight and hopefully get a fix out for you. Thanks for the report and really glad you are liking the pages functionality :-)

**Comment by allmarkedup** [comment]
@dmorgan-fa I've just released v0.8.0 that should fix those issues for you (as well as a few other things). Going to close this now but if you run into any problems just let me know as always. Cheers :-)

**Comment by dmorgan-fa** [comment]
Amazing, thanks Mark! Those fixes resolve the issues I spotted, nice one 👌
