### ISSUE TITLE
Feature Request: Live Code Editor tab

### ISSUE THREAD

**Issue by jonrohan** [allmarkedup/lookbook#82]
It would be awesome if the "Source" tab was content editable, and would rebuild the preview above. 

<img width="911" alt="image" src="https://user-images.githubusercontent.com/54012/165421437-dbf7289d-047a-4c82-98b4-816e4ae2ce6c.png">

**Comment by allmarkedup** [comment]
@jonrohan sorry for the slow reply, I missed this somehow... That would indeed be awesome! But I'm not sure how practical (or safe) it would be to evaluate Ruby code on the fly like that. Makes me a little nervous 😬

I'll keep this open as a feature request in case I get a chance to experiment with it a bit to see what it would involve, but I suspect it's probably out of the scope of what Lookbook can/should do at the moment. Appreciate the suggestion though 👍

**Comment by allmarkedup** [comment]
Hey @jonrohan, I'm going to go ahead and close this now as unfortunately I don't think it's a feature that is going to make it into Lookbook.

I've spent some looking into dynamic code evaluation recently and something like this would be a pretty risky thing to build - if it wasn't done right it could expose the codebases of Lookbook users and I'm not sure I want that responsibility, no matter how cool it would be :-)

You can _kind of_ do something similar using [dynamic preview param fields](https://lookbook.build/guide/previews/params/) but i appreciate it's not quite the same thing.

Thanks for the suggestion anyway!
