### ISSUE TITLE
Refresh not working with inline components

### ISSUE THREAD

**Issue by xdmx** [allmarkedup/lookbook#90]
I'm playing around with ViewComponent and Lookbook and I've created a very simple inline component:
```ruby
class TextComponent < ViewComponent::Base
  def call
    content_tag :p, content
  end
end
```
With a preview:
```ruby
class TextComponentPreview < ViewComponent::Preview
  def default
    render(TextComponent.new) { 'Hello world' }
  end
end
```
It works, but when I change the text I have to stop and restart Puma to have Lookbook showing the change.

Adding a new component also requires to restart the server.

I've tried with another very basic component (`rails g component button --preview`) and when I change the text in the generated `erb` it works/gets updated without having to restart it. But I have to refresh the page, it doesn't autorefresh (I have `config.file_watcher = ActiveSupport::EventedFileUpdateChecker` in the `development.rb` and listen is installed, given that it's a dependency of the gem). I'm not using Docker, M1 nor Apple, but Linux on an AMD cpu. All gems are on the latest versions.

**Comment by allmarkedup** [comment]
Hey @xdmx - thanks for the report, I'm afraid haven't had a chance to look into this yet but will update you as soon as I can if I'm able to replicate and find a fix for this. Thanks for your patience!

**Comment by xdmx** [comment]
I just noticed #98 and I also use puma with 2 workers. I've tried to comment that config line to disable them and now both inline and auto refresh work. The problem seems to be having workers enabled. I'm going to close this issue as it's now a duplicate of the other one
