### ISSUE TITLE
Params are not supported for grouped examples

### ISSUE THREAD

**Issue by xdmx** [allmarkedup/lookbook#91]
I know that this is a [known](https://github.com/allmarkedup/lookbook/blob/main/app/views/lookbook/previews/panels/_params.html.erb#L4=) issue, but I couldn't find any open issue to keep track of this.

My scenario is having a grouped Heading component showing h1-h6 with the same text/content set as a param. It'd be nice to be able to update it and all grouped examples would also update with the new text.

**Comment by allmarkedup** [comment]
@xdmx actually that message in the UI is a little out of date - grouped params are now supported (in a fashion). Any `@param` tags that you add to an example within the group will be made available to the whole group, so any of the examples that are configured to accept them will be updated when changing values in the UI.

I do need to update that message however now! Hope that makes sense and let me know how you get on.
