### ISSUE TITLE
Lookbook v1.0.0 [BETA] - testers wanted!

### ISSUE THREAD

**Issue by allmarkedup** [allmarkedup/lookbook#96]
Hey all. I've been working on a v1.0 release of Lookbook for a little while and it's now getting to the stage where it's ready for testing by any folk who are brave enough to do so :-)

I've just released [v1.0.0.beta.0](https://rubygems.org/gems/lookbook/versions/1.0.0.beta.0) - it should be considered an early beta and is still lacking robust testing but it should be good enough to kick the tires on.

There is more information on the [v1.0-beta branch README](https://github.com/allmarkedup/lookbook/tree/v1.0-beta#readme) but if anyone has any questions about installing or testing the beta or any feedback/comments just drop me a message below (or open a new issue) and I'll get back to you as quickly as I can.

I'll also keep this issue open until the final version is released and post updates here as required.

Many thanks, Mark.

**Comment by tripptuttle** [comment]
I dropped it into my project, and no issues at all thus far! Looks great, thank you for your work on this great project. 

``` ruby
# controllers/lookbook/application_controller.rb
    def generate_theme_overrides
      @theme_overrides = Lookbook::Theme.new(Lookbook.config.ui_theme_overrides).to_css
    end
```
⬆️ Is a great idea, may also be cool to parameterize a few elements so that you could set a few things directly, so one doesn't need to inspect the styles and override. Something like:

`Lookbook.config.ui_theme.header_color = '#ffffff'`
`Lookbook.config.ui_theme.link_color = '#cccccc'`
`Lookbook.config.ui_theme.title_link='/home'`

Don't know if you want contribs, but would be down to help as time allows. And, if there are any specific things you'd like tested, please do let me know!

**Comment by tripptuttle** [comment]
Actually, just noticed you're rolling with CSS vars 💟 , so that makes it just as easy to customize. So, scratch what I said above!

**Comment by tripptuttle** [comment]
I attempted overrides like this, which looks like the format your .to_css method expects. 

```ruby
    overrides = {
      'header': '#fff',
      'header-border': '#fff',
      'header-text': 'black'
    }
    config.lookbook.ui_theme_overrides = overrides
```

But lookbook/config.rb in initialize is throwing an error. 

```shell
mst49@OASIS-MR22D12M sps-ui % rails c
D, [2022-06-13T09:07:44.097948 #24847] DEBUG -- : Stopping listeners
/Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/lookbook-1.0.0.beta.0/lib/lookbook/config.rb:5:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/lookbook-1.0.0.beta.0/lib/lookbook/config.rb:64:in `new'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/lookbook-1.0.0.beta.0/lib/lookbook/config.rb:64:in `ui_theme_overrides='
        from /Users/mst49/workspace/sps-ui/config/application.rb:25:in `<class:Application>'
        from /Users/mst49/workspace/sps-ui/config/application.rb:8:in `<module:SpsUi>'
        from /Users/mst49/workspace/sps-ui/config/application.rb:6:in `<main>'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/railties-7.0.3/lib/rails/command/actions.rb:22:in `require_application!'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/railties-7.0.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/railties-7.0.3/lib/rails/commands/console/console_command.rb:101:in `perform'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/mst49/.rvm/gems/ruby-3.1.2@spsui/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'

```
Happy to test further to help troubleshoot.

**Comment by allmarkedup** [comment]
Hey @tripptuttle, I've just left a comment on your other issue and mentioned the 1.0 beta before I saw this so great to know you are having a play with it anyway!

The theme overrides feature is still a bit of a work in progress which is why I hadn't yet documented it. However you should be able to set them like you did - that is a bug! I'll get that fixed.

If you want to test it even before the fix is done (with the caveat that the overrides variable names/format might still change throughout the beta process!) you should be able to configure it as follows:

```ruby 
config.lookbook.ui_theme_overrides do |theme|
  theme.divider = "#ccc"
  theme['header-text'] = "#eee"
end
```

I will definitely be doing a pass through the variables to rationalise them a bit before the end of the beta - as soon as things are more concrete I'll update the v1.0-beta theme docs with a full list of variable names and configuration information.

Thanks for the bug report and let me know how you get on :-)

**Comment by allmarkedup** [comment]
Closing this issue in favour of moving the conversation to [the discussion here &rarr;](https://github.com/allmarkedup/lookbook/discussions/101)
